spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

  endpoint:
    health:
      show-details: always
