-- Initial schema generated from the current JPA mappings.
-- Existing databases are baselined at version 1; fresh databases execute this migration.

create table advertisements (id bigint not null auto_increment, create_at datetime(6), created_by varchar(255), updated_by varchar(255), update_at datetime(6), active bit not null, description TEXT, endDate date not null, image varchar(255) not null, link varchar(255) not null, sent boolean default false not null, startDate date not null, title varchar(100) not null, course_id bigint, primary key (id)) engine=InnoDB;
create table bank_accounts (id bigint not null auto_increment, create_at datetime(6), created_by varchar(255), updated_by varchar(255), update_at datetime(6), account_holder varchar(150) not null, account_number varchar(50) not null, active bit not null, bank_name varchar(100) not null, is_default bit not null, teacher_id bigint not null, primary key (id)) engine=InnoDB;
create table certificates (id bigint not null auto_increment, create_at datetime(6), created_by varchar(255), updated_by varchar(255), update_at datetime(6), issue_date date not null, verification_code varchar(32) not null, course_id bigint not null, user_id bigint not null, primary key (id)) engine=InnoDB;
create table chapters (id bigint not null auto_increment, create_at datetime(6), created_by varchar(255), updated_by varchar(255), update_at datetime(6), title varchar(255) not null, description MEDIUMTEXT, course_id bigint not null, primary key (id)) engine=InnoDB;
create table conversations (id bigint not null auto_increment, create_at datetime(6), created_by varchar(255), updated_by varchar(255), update_at datetime(6), conversation_key varchar(100), initiator_unread_count integer not null, partner_unread_count integer not null, type enum ('COURSE_QA','SUPPORT') not null, course_id bigint, initiator_id bigint not null, partner_id bigint not null, primary key (id)) engine=InnoDB;
create table course_progress (id bigint not null auto_increment, create_at datetime(6), created_by varchar(255), updated_by varchar(255), update_at datetime(6), completed bit not null, completed_lessons integer not null, progress_percent integer not null, total_lessons integer not null, course_id bigint not null, user_id bigint not null, primary key (id)) engine=InnoDB;
create table courses (id bigint not null auto_increment, create_at datetime(6), created_by varchar(255), updated_by varchar(255), update_at datetime(6), level enum ('ADVANCED','BEGINNER','EXPERT'), description MEDIUMTEXT, duration integer, language varchar(255), points BIGINT DEFAULT 0, status enum ('APPROVED','BANNED','DELETED','DRAFT','PENDING','REJECTED') not null, thumbnail varchar(255), title varchar(255) not null, total_enrollments BIGINT DEFAULT 0, video_url varchar(255), author_id bigint not null, primary key (id)) engine=InnoDB;
create table enrollments (id bigint not null auto_increment, create_at datetime(6), created_by varchar(255), updated_by varchar(255), update_at datetime(6), spent_points bigint not null, status enum ('ACTIVE','COMPLETED','PENDING') not null, course_id bigint not null, user_id bigint not null, primary key (id)) engine=InnoDB;
create table favorites (id bigint not null auto_increment, create_at datetime(6), created_by varchar(255), updated_by varchar(255), update_at datetime(6), course_id bigint not null, user_id bigint not null, primary key (id)) engine=InnoDB;
create table lesson_progress (id bigint not null auto_increment, create_at datetime(6), created_by varchar(255), updated_by varchar(255), update_at datetime(6), completed bit not null, lesson_id bigint not null, user_id bigint not null, primary key (id)) engine=InnoDB;
create table lessons (id bigint not null auto_increment, create_at datetime(6), created_by varchar(255), updated_by varchar(255), update_at datetime(6), content_type enum ('DOCUMENT','VIDEO') not null, content_url varchar(255) not null, description varchar(255), lesson_name varchar(255) not null, chapter_id bigint not null, primary key (id)) engine=InnoDB;
create table messages (id bigint not null auto_increment, create_at datetime(6), created_by varchar(255), updated_by varchar(255), update_at datetime(6), content MEDIUMTEXT not null, type enum ('IMAGE','TEXT') not null, conversation_id bigint not null, sender_id bigint not null, primary key (id)) engine=InnoDB;
create table notifications (id bigint not null auto_increment, create_at datetime(6), created_by varchar(255), updated_by varchar(255), update_at datetime(6), is_read bit not null, message varchar(2000) not null, title varchar(255) not null, url varchar(255), sender_id bigint, user_id bigint not null, primary key (id)) engine=InnoDB;
create table payment (id bigint not null auto_increment, create_at datetime(6), created_by varchar(255), updated_by varchar(255), update_at datetime(6), amount decimal(19,0) not null, bank_code varchar(100), expires_at datetime(6) not null, gateway_transaction_no varchar(30), transaction_id varchar(100) not null, paid_at datetime(6), paymentMethod enum ('MOMO','PAYPAL','VNPAY') not null, pointsReceived bigint not null, response_code varchar(10), status varchar(20) not null, user_id bigint not null, primary key (id)) engine=InnoDB;
create table Permission (name varchar(255) not null, description varchar(255), primary key (name)) engine=InnoDB;
create table point_transactions (id bigint not null auto_increment, create_at datetime(6), created_by varchar(255), updated_by varchar(255), update_at datetime(6), description varchar(255), points bigint not null, transaction_type enum ('ADMIN_CREDIT','ADMIN_DEBIT','BONUS','DEPOSIT','EARN','SPEND','WITHDRAW','WITHDRAW_REFUND') not null, course_id bigint, payment_id bigint, user_id bigint not null, primary key (id)) engine=InnoDB;
create table reviews (id bigint not null auto_increment, create_at datetime(6), created_by varchar(255), updated_by varchar(255), update_at datetime(6), content varchar(255) not null, rating integer, course_id bigint not null, parent_review_id bigint, user_id bigint not null, primary key (id)) engine=InnoDB;
create table roles (id bigint not null auto_increment, create_at datetime(6), created_by varchar(255), updated_by varchar(255), update_at datetime(6), description varchar(255), name varchar(255) not null, primary key (id)) engine=InnoDB;
create table roles_Permission (Role_id bigint not null, permissions_name varchar(255) not null, primary key (Role_id, permissions_name)) engine=InnoDB;
create table users (id bigint not null auto_increment, create_at datetime(6), created_by varchar(255), updated_by varchar(255), update_at datetime(6), address varchar(255), avatar varchar(255), banned bit not null, bio TEXT, certificate varchar(255), cvUrl varchar(255), description MEDIUMTEXT, dob date, email varchar(255) not null, enabled bit not null, expertise varchar(255), facebookLink varchar(255), fullName varchar(255), gender enum ('FEMALE','MALE','OTHER'), googleId varchar(255), password varchar(255), phoneNumber varchar(255), points BIGINT DEFAULT 0 not null, registration_status enum ('APPROVED','NONE','PENDING','REJECTED') not null, username varchar(255) not null, yearsOfExperience float(53), primary key (id)) engine=InnoDB;
create table users_roles (User_id bigint not null, roles_id bigint not null, primary key (User_id, roles_id)) engine=InnoDB;
create table withdrawals (id bigint not null auto_increment, create_at datetime(6), created_by varchar(255), updated_by varchar(255), update_at datetime(6), account_holder varchar(150) not null, account_number varchar(50) not null, amount decimal(19,2) not null, bank_name varchar(100) not null, payment_proof_url varchar(1000), points bigint not null, rejection_reason varchar(500), status enum ('PAID','PENDING','REJECTED') not null, bank_account_id bigint not null, teacher_id bigint not null, primary key (id)) engine=InnoDB;

alter table certificates add constraint uk_certificate_user_course unique (user_id, course_id);
alter table certificates add constraint UKksm6qgavh6pvt85iph4b9r2ms unique (verification_code);
alter table conversations add constraint UKrhxktxhmox42wphyexnh50tow unique (conversation_key);
alter table course_progress add constraint UK6a483281pswh5sdenmv1o0bs unique (user_id, course_id);
create index idx_course_status_created on courses (status, create_at);
create index idx_enrollment_course_created on enrollments (course_id, create_at);
alter table enrollments add constraint uk_user_course unique (user_id, course_id);
alter table favorites add constraint uk_favorite_user_course unique (user_id, course_id);
alter table lesson_progress add constraint UK7lok1iwll7jsobapv1rmr563 unique (user_id, lesson_id);
create index idx_message_conversation_created on messages (conversation_id, create_at);
create index idx_notification_user_created on notifications (user_id, create_at);
create index idx_notification_user_read on notifications (user_id, is_read);
create index idx_payment_user_created on payment (user_id, create_at);
create index idx_payment_status_created on payment (status, create_at);
alter table payment add constraint UKpahd10uaajt7s1t8miaxsya1d unique (gateway_transaction_no);
alter table payment add constraint UKtacis04bqalsngo46yvxlo7yb unique (transaction_id);
create index idx_point_transaction_user_created on point_transactions (user_id, create_at);
create index idx_point_transaction_type_created on point_transactions (transaction_type, create_at);
alter table point_transactions add constraint UKar3r9svdbof02g27soamqib0n unique (payment_id);
create index idx_review_course_parent_created on reviews (course_id, parent_review_id, create_at);
alter table roles add constraint UKofx66keruapi6vyqpv6f2or37 unique (name);
alter table users add constraint UK6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table users add constraint UKjd7fraw9jvmvjpng1obfco83f unique (googleId);
alter table users add constraint UKkwds03ohobcd8p6eowkw0f5bm unique (phoneNumber);
alter table users add constraint UKr43af9ap4edm43mmtq01oddj6 unique (username);
create index idx_withdrawal_teacher_created on withdrawals (teacher_id, create_at);
create index idx_withdrawal_status_created on withdrawals (status, create_at);

alter table advertisements add constraint FKfqpk2fob1wjv9kttjgrucy0tv foreign key (course_id) references courses (id);
alter table bank_accounts add constraint FK5v9y9nv8fc384b5ou6tn4u7kw foreign key (teacher_id) references users (id);
alter table certificates add constraint FKs5rftqrsgkog7h4piv3f7a9s6 foreign key (course_id) references courses (id);
alter table certificates add constraint FKd3f6enpb3p3xovee9klklf05r foreign key (user_id) references users (id);
alter table chapters add constraint FK6h1m0nrtdwj37570c0sp2tdcs foreign key (course_id) references courses (id);
alter table conversations add constraint FKhiow7kb4svq8dr8y69i5i5ipn foreign key (course_id) references courses (id);
alter table conversations add constraint FK2vdu3tbwqmckxxklac8427d9r foreign key (initiator_id) references users (id);
alter table conversations add constraint FKkh32jhhg3s8t66b20xst9ywu6 foreign key (partner_id) references users (id);
alter table course_progress add constraint FK3h5cnaawt3y91eeaaloat1swr foreign key (course_id) references courses (id);
alter table course_progress add constraint FKmootcccgd4bqe8cjtma7stkp1 foreign key (user_id) references users (id);
alter table courses add constraint FKhbo41uaq9qyi5ora71hq2oyah foreign key (author_id) references users (id);
alter table enrollments add constraint FKho8mcicp4196ebpltdn9wl6co foreign key (course_id) references courses (id);
alter table enrollments add constraint FK3hjx6rcnbmfw368sxigrpfpx0 foreign key (user_id) references users (id);
alter table favorites add constraint FK18gn3il3auwv7m74x50p9y479 foreign key (course_id) references courses (id);
alter table favorites add constraint FKk7du8b8ewipawnnpg76d55fus foreign key (user_id) references users (id);
alter table lesson_progress add constraint FKqwr70bkn0j6gok1y4op9jns8y foreign key (lesson_id) references lessons (id);
alter table lesson_progress add constraint FKhxwj6gbacmwi2768sceg602uf foreign key (user_id) references users (id);
alter table lessons add constraint FKmb78vk1f2oljr16oj1hpo45ma foreign key (chapter_id) references chapters (id);
alter table messages add constraint FKt492th6wsovh1nush5yl5jj8e foreign key (conversation_id) references conversations (id);
alter table messages add constraint FK4ui4nnwntodh6wjvck53dbk9m foreign key (sender_id) references users (id);
alter table notifications add constraint FK13vcnq3ukas06ho1yrbc5lrb5 foreign key (sender_id) references users (id);
alter table notifications add constraint FK9y21adhxn0ayjhfocscqox7bh foreign key (user_id) references users (id);
alter table payment add constraint FKmi2669nkjesvp7cd257fptl6f foreign key (user_id) references users (id);
alter table point_transactions add constraint FK98wdjm9v6g31c8jiqx7tvhy7v foreign key (course_id) references courses (id);
alter table point_transactions add constraint FKg4g5ko815c4s042ye8im0acjg foreign key (payment_id) references payment (id);
alter table point_transactions add constraint FKcqbvxpskb8p7mko50hokltu5b foreign key (user_id) references users (id);
alter table reviews add constraint FKccbfc9u1qimejr5ll7yuxbtqs foreign key (course_id) references courses (id);
alter table reviews add constraint FKjvbonqfdvou0pln3uxbkvtxks foreign key (parent_review_id) references reviews (id);
alter table reviews add constraint FKcgy7qjc1r99dp117y9en6lxye foreign key (user_id) references users (id);
alter table roles_Permission add constraint FK9jjg4hdod2ngi4horaj8f69g3 foreign key (permissions_name) references Permission (name);
alter table roles_Permission add constraint FK3649dbpu5aqeyis4trabdx4ab foreign key (Role_id) references roles (id);
alter table users_roles add constraint FKa62j07k5mhgifpp955h37ponj foreign key (roles_id) references roles (id);
alter table users_roles add constraint FKe6k7h92pkxjim6t1176b7h95x foreign key (User_id) references users (id);
alter table withdrawals add constraint FKi5bj2id876metym5i112m4xyv foreign key (bank_account_id) references bank_accounts (id);
alter table withdrawals add constraint FKmwg6o996leypvvoha5fj0xxdj foreign key (teacher_id) references users (id);
